namespace :cas do
  desc "CA profiles that can be referenced"
  task seed_ejbca_profiles: :environment do
    if ENV['RESET']
      CasCertificate.delete_all
      Ca.where{ref!="0"}.delete_all
    end
    Ca.create!([{
                      ref: "1000",
                      friendly_name: "CertLock SSL RSA 4096 (EV)",
                      profile_name: "CertLock-SubCA-EV-SSL-RSA-4096",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:evssl],
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1001",
                      friendly_name: "CertLock SSL RSA 4096 (DV)",
                      profile_name: "CertLock-SubCA-SSL-RSA-4096",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:dvssl],
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1002",
                      friendly_name: "CertLock SSL RSA 4096 (OV)",
                      profile_name: "CertLock-SubCA-SSL-RSA-4096",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:ovssl],
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1003",
                      friendly_name: "CertLock SSL ECC (DV)",
                      profile_name: "CertLockECCSSLsubCA",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:dvssl],
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1004",
                      friendly_name: "CertLock SSL ECC (OV)",
                      profile_name: "CertLockECCSSLsubCA",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:ovssl],
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1005",
                      friendly_name: "CertLock SSL ECC (EV)",
                      profile_name: "CertLockEVECCSSLsubCA",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:evssl],
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1006",
                      friendly_name: "CertLockEVROOTCAECC",
                      profile_name: "CertLockEVROOTCAECC",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1007",
                      friendly_name: "CertLockEVROOTCARSA",
                      profile_name: "CertLockEVROOTCARSA",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1008",
                      friendly_name: "CertLockROOTCAECC",
                      profile_name: "CertLockROOTCAECC",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1009",
                      friendly_name: "CertLockROOTCARSA",
                      profile_name: "CertLockROOTCARSA",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::CERTLOCK_CA
                  },
                  {
                      ref: "1100",
                      friendly_name: "ECOsslcom-RootCA-ECC-384-R1",
                      profile_name: "ECOsslcom-RootCA-ECC-384-R1",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::ECOSSL_CA
                  },
                  {
                      ref: "1101",
                      friendly_name: "ECOsslcom-RootCA-RSA-4096-R1",
                      profile_name: "ECOsslcom-RootCA-RSA-4096-R1",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::ECOSSL_CA
                  },
                  {
                      ref: "1200",
                      friendly_name: "ManagementCA",
                      profile_name: "ManagementCA",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::MANAGEMENT_CA
                  },
                  {
                      ref: "0001",
                      friendly_name: "SSL.com EV CS RSA 4096",
                      profile_name: "SSL.com-EV-codeSigning-Intermediate-RSA-4096",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ekus: Ca::EKUS[:code_signing],
                      end_entity: Ca::END_ENTITY[:evcs],
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0002",
                      friendly_name: "SSLcom-RootCA-ECC-384-R1",
                      profile_name: "SSLcom-RootCA-ECC-384-R1",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0003",
                      friendly_name: "SSLcom-RootCA-ECC-384-R2",
                      profile_name: "SSLcom-RootCA-ECC-384-R2",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0004",
                      friendly_name: "SSLcom-RootCA-EV-ECC-384-R1",
                      profile_name: "SSLcom-RootCA-EV-ECC-384-R1",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0005",
                      friendly_name: "SSLcom-RootCA-EV-ECC-384-R2",
                      profile_name: "SSLcom-RootCA-EV-ECC-384-R2",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0006",
                      friendly_name: "SSL.com SSL ECC 384 (EV)",
                      profile_name: "SSLcom-SubCA-EV-SSL-ECC-384-R1",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:evssl]
                  },
                  {
                      ref: "0007",
                      friendly_name: "SSL.com SSL ECC 384 (DV)",
                      profile_name: "SSLcom-SubCA-SSL-ECC-384-R1",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:dvssl]
                  },
                  {
                      ref: "0008",
                      friendly_name: "SSL.com SSL ECC 384 (OV)",
                      profile_name: "SSLcom-SubCA-SSL-ECC-384-R1",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:ovssl]
                  },
                  {
                      ref: "0009",
                      friendly_name: "SSLcom-RootCA-EV-RSA-4096-R2",
                      profile_name: "SSLcom-RootCA-EV-RSA-4096-R2",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0010",
                      friendly_name: "SSLcom-RootCA-EV-RSA-4096-R3",
                      profile_name: "SSLcom-RootCA-EV-RSA-4096-R3",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0011",
                      friendly_name: "SSLcom-RootCA-RSA-4096-R1",
                      profile_name: "SSLcom-RootCA-RSA-4096-R1",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0012",
                      friendly_name: "SSLcom-RootCA-RSA-4096-R2",
                      profile_name: "SSLcom-RootCA-RSA-4096-R2",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0013",
                      friendly_name: "SSL.com CS RSA 4096",
                      profile_name: "SSLcom-SubCA-CodeSigning-RSA-4096-R1",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:code_signing]],
                      end_entity: Ca::END_ENTITY[:cs]
                  },
                  {
                      ref: "0014",
                      friendly_name: "SSL.com EV CS RSA 4096",
                      profile_name: "SSLcom-SubCA-EV-CodeSigning-RSA-4096-R2",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:code_signing]],
                      end_entity: Ca::END_ENTITY[:evcs]
                  },
                  {
                      ref: "0015",
                      friendly_name: "SSL.com SSL RSA 4096 R2 (EV)",
                      profile_name: "SSLcom-SubCA-EV-SSL-RSA-4096-R2",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:evssl]
                  },
                  {
                      ref: "0016",
                      friendly_name: "SSL.com EV TimeStamping RSA 4096",
                      profile_name: "SSLcom-SubCA-EV-TimeStamping-RSA-4096-R1",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:time_stamping]]
                  },
                  {
                      ref: "0017",
                      friendly_name: "SSL.com SSL RSA 4096 (DV)",
                      profile_name: "SSLcom-SubCA-SSL-RSA-4096-R1",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:dvssl]
                  },
                  {
                      ref: "0018",
                      friendly_name: "SSL.com SSL RSA 4096 (OV)",
                      profile_name: "SSLcom-SubCA-SSL-RSA-4096-R1",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:ovssl]
                  },
                  {
                      ref: "0019",
                      friendly_name: "SSLcomEVROOTCARSA",
                      profile_name: "SSLcomEVROOTCARSA",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "RootCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA
                  },
                  {
                      ref: "0020",
                      friendly_name: "SSLcomEVRSASSLsubCA",
                      profile_name: "SSLcomEVRSASSLsubCA",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:server]],
                      end_entity: Ca::END_ENTITY[:evssl]
                  },
                  {
                      ref: "0021",
                      friendly_name: "NAESB Client Cert Rudimentary Assurance",
                      profile_name: "OV_RSA_NAESB_RA_CERT",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:client]],
                      end_entity: Ca::END_ENTITY[:ov_client]
                  },
                  {
                      ref: "0022",
                      friendly_name: "NAESB Client Cert Basic Assurance",
                      profile_name: "OV_RSA_NAESB_BA_CERT",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:client]],
                      end_entity: Ca::END_ENTITY[:ov_client]
                  },
                  {
                      ref: "0023",
                      friendly_name: "NAESB RSA Client Cert High Assurance",
                      profile_name: "OV_RSA_NAESB_HA_CERT",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:client]],
                      end_entity: Ca::END_ENTITY[:ov_client]
                  },
                  {
                      ref: "0024",
                      friendly_name: "NAESB RSA Client Cert Medium Assurance",
                      profile_name: "OV_RSA_NAESB_MA_CERT",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "SubCa",
                      caa_issuers: ["ssl.com"],
                      host: "https://192.168.100.5:8442/restapi",
                      admin_host: "https://192.168.100.5:8443",
                      ca_name: Ca::SSLCOM_CA,
                      ekus: [Ca::EKUS[:client]],
                      end_entity: Ca::END_ENTITY[:ov_client]
                  },
                  {
                      ref: "2000",
                      friendly_name: "DV_RSA_SERVER_CERT",
                      profile_name: "DV_RSA_SERVER_CERT",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "2001",
                      friendly_name: "OV_RSA_SERVER_CERT",
                      profile_name: "OV_RSA_SERVER_CERT",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "2002",
                      friendly_name: "EV_RSA_SERVER_CERT",
                      profile_name: "EV_RSA_SERVER_CERT",
                      algorithm: "rsa",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "2003",
                      friendly_name: "DV_ECC_SERVER_CERT",
                      profile_name: "DV_ECC_SERVER_CERT",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "2004",
                      friendly_name: "OV_ECC_SERVER_CERT",
                      profile_name: "OV_ECC_SERVER_CERT",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "2005",
                      friendly_name: "EV_ECC_SERVER_CERT",
                      profile_name: "EV_ECC_SERVER_CERT",
                      algorithm: "ecc",
                      size: 384,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "3000",
                      friendly_name: "DV_SERVER_CERT_EE",
                      profile_name: "DV_SERVER_CERT_EE",
                      algorithm: "",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "3001",
                      friendly_name: "OV_SERVER_CERT_EE",
                      profile_name: "OV_SERVER_CERT_EE",
                      algorithm: "",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "3002",
                      friendly_name: "EV_SERVER_CERT_EE",
                      profile_name: "EV_SERVER_CERT_EE",
                      algorithm: "",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "3003",
                      friendly_name: "CS_CERT_EE",
                      profile_name: "CS_CERT_EE",
                      algorithm: "",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "3004",
                      friendly_name: "EV_CS_CERT_EE",
                      profile_name: "EV_CS_CERT_EE",
                      algorithm: "",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  },
                  {
                      ref: "3005",
                      friendly_name: "OV_CLIENTAUTH_CERT_EE",
                      profile_name: "OV_CLIENTAUTH_CERT_EE",
                      algorithm: "",
                      size: 4096,
                      description: "",
                      type: "EndEntityProfile"
                  }])
    Certificate.all.each {|cert|
      Ca.all.each {|ca|
        unless ca.is_a?(EndEntityProfile) or ca.is_a?(RootCa) or ca.ekus.blank?
          if cert.is_evcs? and ca.end_entity==(Ca::END_ENTITY[:evcs])
            cert.ca_certificates.create(ca_id: ca.id,status: CasCertificate::STATUS[:active])
          elsif cert.is_cs? and ca.end_entity==(Ca::END_ENTITY[:cs])
            cert.ca_certificates.create(ca_id: ca.id,status: CasCertificate::STATUS[:active])
          elsif  cert.is_dv? or cert.is_ov? or cert.is_ev?
            if ca.end_entity==(Ca::END_ENTITY[:dvssl])
              cert.ca_certificates.create(ca_id: ca.id,status: CasCertificate::STATUS[:active])
            elsif (cert.is_ov? or cert.is_ev?) and ca.end_entity==(Ca::END_ENTITY[:ovssl])
              cert.ca_certificates.create(ca_id: ca.id,status: CasCertificate::STATUS[:active])
            elsif cert.is_ev? and ca.end_entity==(Ca::END_ENTITY[:evssl])
              cert.ca_certificates.create(ca_id: ca.id,status: CasCertificate::STATUS[:active])
            end
          end
        end
      }
    }
  end
end
