version: "2"

plugins:
  brakeman:
    enabled: true
    checks:
      no_attr_accessible:
        enabled: false
  bundler-audit:
    enabled: false # we are using dependabot
  csslint:
    enabled: true
  coffeelint:
    enabled: false # not currently using coffeescript
  duplication:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: false
  git-legal:
    enabled: true
  haml-lint:
    enabled: true
  reek:
    enabled: false # Duplicates Rubocop
  rubocop:
    enabled: true
    checks:
      Rubocop/Layout/AlignHash:
        enabled: false
      Rubocop/Lint/UselessAssignment:
        enabled: false
      Rubocop/Metrics/BlockNesting:
        enabled: false
      Rubocop/Style/RedundantFreeze:
        enabled: false
  sass-lint:
    enabled: true
    checks:
      no-ids:
        enabled: false
      single-line-per-selector:
        enabled: false

exclude_patterns:
  - "config/"
  - "db/"
  - "**/node_modules/"
  - "test/"
  - "**/vendor/"
  - "*.md"
  - ".*"
  - 'vendor/**/*'
  - 'tmp/**/*'
  - 'lib/**/*'
  - 'bin/*'
  - 'db/**/*'
  - 'script/'
  - 'features/'