version: "2"

plugins:
  brakeman:
    enabled: true
    checks:
      no_attr_accessible:
        enabled: false
      mass_assign_call:
        enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: true
  coffeelint:
    enabled: false # not currently using coffeescript
  duplication:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: false
  git-legal:
    enabled: true
  haml-lint:
    enabled: true
    checks:
      HamlLint/LeadingCommentSpace:
        enabled: false
  reek:
    enabled: false # Duplicates Rubocop
  rubocop:
    enabled: true
    channel: rubocop-0-79
    checks:
      Rubocop/Layout/AlignHash:
        enabled: false
      Rubocop/Lint/UselessAssignment:
        enabled: false
      Rubocop/Metrics/BlockNesting:
        enabled: false
      Rubocop/Style/RedundantFreeze:
        enabled: false
      Rubocop/Style/BracesAroundHashParameters:
        enabled: false
      Rubocop/Layout/SpaceInsideHashLiteralBraces:
        enabled: false
      Rubocop/Naming/HeredocDelimiterNaming:
        enabled: false
      Rubocop/Layout/ExtraSpacing:
        enabled: false
      Rubocop/Layout/IndentHeredoc:
        enabled: false
      Rubocop/Rails/FilePath:
        enabled: false
  sass-lint:
    enabled: true
    checks:
      no-ids:
        enabled: false
      single-line-per-selector:
        enabled: false

exclude_patterns:
- "db/"
- "**/node_modules/"
- "**/vendor/"
- "*.md"
- ".*"
- 'vendor/**/*'
- 'tmp/**/*'
- 'lib/**/*'
- 'bin/*'
- 'db/**/*'
- 'script/'
- 'features/'
- 'Vagrantfile'
