fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 2.3.3     # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'app/**/*':
    - Style/StringLiterals
    - Style/TrailingCommaInArrayLiteral
    - Style/TrailingCommaInHashLiteral
    - Layout/SpaceInsideReferenceBrackets
    - Standard/SemanticBlocks
    - Layout/ArrayAlignment
    - Layout/SpaceInsideBlockBraces
    - Layout/SpaceInsideHashLiteralBraces
    - Layout/SpaceInsideArrayLiteralBrackets
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'test/**/*':
    - Layout/AlignHash