source 'http://rubygems.org'

gem 'rails', '~> 4.2.7.1'
gem 'sprockets'
gem 'protected_attributes'
gem 'responders', '~> 2.0'
gem 'dynamic_form'
gem 'mysql2'
gem 'workflow'
gem "rabl"
gem 'pry-rails'
gem 'awesome_print'
gem 'activemerchant'
gem 'money', '2.1.0'
gem 'rack-ssl-enforcer'
gem 'will_paginate'
gem 'haml', '>= 3.1.alpha.50'
gem 'declarative_authorization'
gem "authlogic"
gem "savon", '~> 2.0'
gem 'zip-zip'
gem 'rb-inotify', :require => false
gem 'aws-sdk', '~> 2.0'
gem "paperclip", '~> 5.3.0'
gem 'xml-simple'
gem 'json', '~> 1.8.1'
gem 'easy_roles'
gem 'squeel'
gem 'yui-compressor'
#Commented out while converting to pipeline
# gem 'jammit'
gem "config"
gem 'uuidtools'
gem 'radix62'
gem 'whenever', require: false
gem 'openssl-extensions', :require => 'openssl-extensions/all'
gem 'simpleidn'
gem "oauth-plugin", ">= 0.4.0.pre1"
gem "therubyracer", '~> 0.12.0', platform: :ruby
gem "libv8", '~> 3.16.14.0'
# gem 'request_exception_handler'
gem 'rvm-capistrano'
gem 'newrelic_rpm'
gem 'dalli'
gem 'attr_encrypted', '>= 3.0.3'
gem 'delayed_job_active_record'
gem "daemons"
gem 'delayed_job_groups_plugin'
gem 'delayed-web'
gem 'public_suffix'
gem 'rack-cors', :require => 'rack/cors'
gem 'cancan'
gem 'unscoped_associations'
gem 'nokogiri'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc',          group: :doc
gem 'airbrake', '~> 8.1'
gem 'rails-observers'
gem 'actionpack-action_caching', '~> 1.1', '>= 1.1.1'
gem 'sass-rails'
gem 'bootstrap'
gem 'compass-rails'
gem 'select2-rails'
gem 'stripe'
gem 'json-schema'
gem 'rails-api'
gem 'jsonapi-serializers'
gem 'api-pagination'
gem 'rubyzip', '~> 1.2.1'
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'u2f'
gem 'duo_web', '~> 1.0'
# gem 'simple_captcha2', require: 'simple_captcha'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'font-awesome-rails'
gem 'acts_as_tree'
gem 'whois', '~> 4.0'
gem 'whois-parser'
gem 'where-or'
# gem "skylight"
gem 'authy'
gem 'mailboxer'
gem 'memoist'
# gem 'countries'

group :development do
  gem 'foreman'
  gem 'dotenv-rails'
  gem 'guard-livereload'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'spring-commands-testunit'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'byebug'
end

group :development, :test do
  gem 'builder'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'pry-remote'
  gem 'ruby_parser'
  gem 'ruby-odbc'
end

group :test do
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'capybara_minitest_spec'
  gem 'capybara-screenshot'
  gem 'chromedriver-helper'
  gem 'database_cleaner'
  gem 'faker'
  gem 'guard'
  gem 'guard-minitest'
  gem 'headless'
  gem 'minitest-focus'
  gem 'minitest-rails'
  gem 'minitest-reporters'
  gem 'mocha'
  gem 'rack_session_access'
  gem 'selenium-webdriver'
  gem 'terminal-notifier-guard'
end

group :assets do
  gem 'uglifier', '4.1.8'
end

gem 'httparty'
