site: 'remote'
root_subdomain: "www"
actionmailer_host: "www.certassure.com"
community_name: "CertAssure"
community_domain: "www.certassure.com"
api_domain: "api.certassure.com"
test_api_domain: "api-test.certassure.com"
dev_api_domain: "api.certassure.local"
dev_test_api_domain: "api-test.certassure.local"
support_domain: "support.certassure.com"
community_tagline: "copyright 2015"
merchant_name: "SSL.com"
community_description:  "SSL.com simplifies SSL certificate procurement and implementation. Integrate security into your websites and applications with SSL.com certificates."
support_email:  "support@certassure.com"
meta_description: "Wildcard SSL Certificates &amp; 2048-Bit Extended Validation SSL Certificate Authentication. Strong Secure Sockets Layer Https Encryption for Network Security."
meta_keywords: "What is SSL, Best SSL, How SSL works, Learn SSL, SSL Security, Secured SSL"
meta_title: "SSL Digital Certificate Authority - Authentication & Encryption"
allow_windows_cr: false
show_advertising: false
closed_beta_mode: false
track_visitors: false
single_server_license_only: true
show_csr_submit_on_buy_page: false
enable_google_translate: false
enable_affiliate_program: false
enable_exception_notifier: true
offer_trial: false
minimum_deposit_amount: 10.00
ucc_initial_domains_block: 3
ucc_max_domains: 200
cert_expiration_threshold_days: 365
expiring_threshold: 60
intermediate_certs_path: "<%=Rails.root%>/public/cert_bundles/"
#header_phone_numbers: "toll free: 1-877-SSL-Secure (1-877-775-7328); intl: +1-SSL-Certificate (+1-775-237-8434)"
header_phone_numbers: "+1-SSL-Certificate (+1-775-237-8434) or toll free 877-SSL-Secure"
corp_name: "SSL Corp"
corp_address1: "3100 Richmond Ave"
corp_address2: "Suite 503"
corp_city: "Houston"
corp_state: "TX"
corp_zip: "77098"
corp_phone_tag: "1 844 SSL FIRE (1 844 775 3473)"
corp_tollfree_tag: "1 844 SSL FIRE (1 844 775 3473)"
corp_fax: "832-201-7706"
mail_address1: "1769 Hillsdale Ave."
mail_address2: "Suite 24472"
mail_city: "San Jose"
mail_state: "CA"
mail_zip: "95154"
public_header_phone_number: "I.844.SSL.FIRE"
# Comment this out if you want to infer the locale
# off of the http headers
community_locale: "en"
#absolute location of member's files
member_files_location: "private"
production_public_location: "public/"
production_private_location: "private/"
csr_parser_wsdl: 'http://ws.ssltools.com/sslutils/wsdl/SSLUtils.wsdl'
certificate_parser_wsdl: 'http://ws.ssltools.com/sslutils/wsdl/SSLUtils.wsdl'

installation_support_pages: "http://info.certassure.com"

comodo_api_username: 'certassureneal'
comodo_api_password: '@Certassure15'
ca_certificate_id_ev: "552"
ca_certificate_id_ov: "551"
ca_certificate_id_dv: "550"
ca_certificate_id_client: "556"
ca_certificate_id_code_signing: "557"

authorize_net_key: '2s9n7LCP'
authorize_net_transaction_id: '27PD3Czbb343hY5R'
p_authorize_net_key: '8yhUk64R79'
p_authorize_net_transaction_id: '539Sa8H5jc632gTh'
olark_id: '6197-594-10-8504'

paypal_express:
  development:
   username: "leo-facilitator_api1.ssl.com"
   password: "1373405411"
   signature: "AQU0e5vuZCvSg-XJploSa.sGUDlpAJk4MS-StTGW3nR1cLoXYinXNPFz"
  production:
   username: "neal-facilitator_api1.certassure.com"
   password: "D8V4AEK5MGDGF35Q"
   signature: "ArNcVBXHSF0WcWk3MEwFFPbyZkYIAxVQyQRWzDg87EMckBedPrWGftlF"

# 'local' for openssl, 'remote' to use java SOAP
csr_parser: local

excluded_titles:
  ["--- Personal Basic\n...\n", "--- Personal Pro\n...\n", "--- Personal Enterprise\n...\n", "--- Personal Business\n...\n",
  "--- Premium Multi-subdomain SSL\n...\n", "Migrated SSL"] #,"--- Code Signing\n...\n"

api_product_codes: 
  {100: "evucc256sslcom", 101: "ucc256sslcom", 102: "ev256sslcom",
   103: "ov256sslcom", 104: "dv256sslcom", 105: "wc256sslcom", 106: "basic256sslcom",
   107: "premium256sslcom",
   204: "evucc256sslcom", 202: "ucc256sslcom", 203: "ev256sslcom",
   200: "basic256sslcom", 201: "wc256sslcom", 300: "personalbasic256sslcom",
   301: "personalpro256sslcom", 302: "personalbusiness256sslcom", 303: "personalenterprise256sslcom",
   350: "codesigning256sslcom"}

subca_mapping:
  dv: {product: "assureguard-dv", label: "AssureGuard DV"}
  ov: {product: "assureguard-ov", label: "AssureGuard OV", info: "http://www.masongraphics.co.za/ov_certificate.html"}
  ev: {product: "assureguard-ev", label: "AssureGuard EV", info: "http://www.masongraphics.co.za/ev_certificate.html"}
  evucc: {product: "assureguard-evucc", label: "AssureGuard EV SAN/UCC", info: "http://www.masongraphics.co.za/domain_validation.html"}
  ucc: {product: "assureguard-ucc", label: "AssureGuard SAN/UCC", info: "http://www.masongraphics.co.za/uss_san.html"}
  wildcard: {product: "assureguard-wildcard", label: "AssureGuard Wildcard", info: "http://www.masongraphics.co.za/wildcard_ssl.html"}

send_dv_first: true

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
featured_writer_label: 'Featured Writer'
allow_anonymous_commenting: false
require_captcha_on_signup: true
recaptcha_pub_key: 6Lch9QYAAAAAAMKfJMXiclR-6EuiZRBr8o98dHdF
recaptcha_priv_key: 6Lch9QYAAAAAAAlWpfQKWpn7eTkc3f2FWhv4fVIG
# uncomment these keys if you turn captcha on for commenting or signup
studio_fee_rate: .3
affiliate_cookie_days: 30
affiliate_program: "shareasale"
cart_cookie_days: 30
reserved_logins: ['administrator', 'sysadmin', 'admin', 'support', 'sales', 'info', 'eroslife', 'systemadmin', 'moderator', 'operator']
exclude_amex: true
number_of_captured_frames: 20
max_content_size: 10
max_num_releases: 100
affiliate_param_key: 'code/r-'
thumbnail_tagline_size: 32
allow_reseller_validation: true
sync_aid_li_and_cart: false
browser_acceptance: "99.9%"
notify_address: "support@certassure.com"
disable_links_banner: false

from_email:
  orders: 'orders@certassure.com'
  activations: 'noreply@certassure.com'
  no_reply: 'noreply@certassure.com'

photo:
  missing_micro: '/plugin_assets/community_engine/images/icon_missing_micro.gif'
  missing_thumb: '/plugin_assets/community_engine/images/icon_missing_thumb.gif'
  missing_medium: "/plugin_assets/community_engine/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "100x100!", medium: "290x320!", large: "664>", micro: "50x50!"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

feature:
  use_thumbs: true
  dimensions: [150, 635]
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    max_size: 1
    thumbnails: {thumb: '45x45!', large: '635x150!'}
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

clipping:
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    max_size: 3
    thumbnails: {thumb: "100x100!", medium_square: "200x200!", medium: "200>"}
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

theme: picclet