embed_assets: datauri

javascripts:
  common:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js
    - public/javascripts/jquery.livequery.js
    - public/javascripts/multifile/jquery.MetaData.js
    - public/javascripts/multifile/jquery.MultiFile.pack.js
    - public/javascripts/multifile/jquery.blockUI.js
    - public/javascripts/jquery-ui-1.8.7.custom.min.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/jquery.json-2.2.min.js
    - public/javascripts/jquery.tooltip.min.js
    - public/javascripts/jCal.js
    - public/javascripts/datejs.js

  shared:
    - public/javascripts/jquery.js
    - public/javascripts/jquery.prettyPhoto.js
    - public/javascripts/jquery.prettyLoader.js
    - public/javascripts/jquery.prettyPopin.js
    - public/javascripts/jquery.form.js

stylesheets:
  ssl_com:
    - public/stylesheets/compiled/main.css
    - public/stylesheets/compiled/master.css
  certassure:
    - public/stylesheets/compiled/certassure.css
  common:
    - public/stylesheets/jquery-ui-1.8.7.custom.css
    - public/stylesheets/jquery.tooltip.css
    - public/stylesheets/prettyPhoto.css
    - public/stylesheets/prettyLoader.css
    - public/stylesheets/prettyPopin.css
  print:
    - public/stylesheets/print.css
  ie:
    - public/stylesheets/compiled/ie.css
  ie8:
    - public/stylesheets/compiled/ie8.css
  site_report:
    - public/stylesheets/compiled/site_report.css
    - public/stylesheets/prettyPhoto.css
  buy_now:
    - public/stylesheets/compiled/buy_now.css
  ssl_seal:
    - public/stylesheets/compiled/ssl_seal.css
