# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  encoding: utf8
  #reconnect: true
  port: 3306
  pool: 10
  username: ssl_db
  password: kama2jama2
  socket: /var/run/mysqld/mysqld.sock
<%if defined? JRUBY_VERSION%>
  adapter: jdbcmysql
  #use when remote db source
  host: 10.208.174.45
  database: ssl_com_production
<%else%>
  adapter: mysql
  database: ssl_com_development
  #use when remote db source
#  host: 75.101.161.230
#  database: ssl_com_production
<%end%>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ssl_com_test
  pool: 5
  username: ssl_db
  password: kama2jama2
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ssl_com_production
  pool: 5
  username: ssl_db
  password: kama2jama2
  socket: /var/run/mysqld/mysqld.sock


cucumber:
  <<: *TEST

<%unless Rails.env=='test'%>
ssl_store_mssql:
  adapter: sqlserver
  mode: odbc
  encoding: utf8
  username: sa
  password: staticgoat
  dsn: ssl_store_legacy
<%end%>
