development:
  access_key_id:     <%= Rails.application.secrets.s3_access_key_id %>
  secret_access_key: <%= Rails.application.secrets.s3_secret_access_key %> 
production:
  access_key_id:     <%= Rails.application.secrets.s3_access_key_id %>
  secret_access_key: <%= Rails.application.secrets.s3_secret_access_key %>
