development:
  access_key_id: 0A9RS683ZWBD5QFKXJ82
  secret_access_key: AEqFfZC+EyeVWhYJlP9Wclm7Wl36GqoJfnHrN+85
production:
  access_key_id: 0A9RS683ZWBD5QFKXJ82
  secret_access_key: AEqFfZC+EyeVWhYJlP9Wclm7Wl36GqoJfnHrN+85
