site: 'remote'
root_subdomain: "www"
actionmailer_host: "www.ssl.com"
community_name: "SSL.com"
community_tagline: "copyright 2011"
community_description:  "SSL.com simplifies SSL certificate procurement and implementation. Integrate security into your websites and applications with SSL.com certificates."
support_email:  "support@ssl.com"
meta_description: "Wildcard SSL Certificates &amp; 2048-Bit Extended Validation SSL Certificate Authentication. Strong Secure Sockets Layer Https Encryption for Network Security."
meta_keywords: "What is SSL, Best SSL, How SSL works, Learn SSL, SSL Security, Secured SSL"
meta_title: "SSL Digital Certificate Authority - Authentication &amp; Encryption"
show_advertising: false
closed_beta_mode: false
track_visitors: false
single_server_license_only: true
show_csr_submit_on_buy_page: false
enable_google_translate: false
enable_exception_notifier: true
offer_trial: true
minimum_deposit_amount: 10.00
ucc_initial_domains_block: 3
ucc_max_domains: 200
cert_expiration_threshold_days: 365
expiring_threshold: 60
intermediate_certs_path: "<%=Rails.root%>/public/cert_bundles/"
#header_phone_numbers: "toll free: 1-877-SSL-Secure (1-877-775-7328); intl: +1-SSL-Certificate (+1-775-237-8434)"
header_phone_numbers: "+1-SSL-Certificate (+1-775-237-8434) or toll free 877-SSL-Secure"
corp_name: "SSL Corp"
corp_address1: "2617C W Holcombe Blvd"
corp_address2: "Suite 286"
corp_city: "Houston"
corp_state: "TX"
corp_zip: "77025-1601"
corp_phone_tag: "+1-SSL-Certificate (+1-775-237-8434)"
corp_tollfree_tag: "877-SSL-Secure (877-775-7328)"
corp_fax: "832-201-7706"
mail_address1: "2617C W Holcombe Blvd"
mail_address2: "Suite 286"
mail_city: "Houston"
mail_state: "TX"
mail_zip: "77025-1601"
# Comment this out if you want to infer the locale
# off of the http headers
community_locale: "en"
#absolute location of member's files
member_files_location: "private"
production_public_location: "public/"
production_private_location: "private/"
csr_parser_wsdl: 'http://ws.ssltools.com/sslutils/wsdl/SSLUtils.wsdl'
certificate_parser_wsdl: 'http://ws.ssltools.com/sslutils/wsdl/SSLUtils.wsdl'

installation_support_pages: "http://info.ssl.com/default.aspx?cNode=2T0V6X&pNodes=8P3K3M"

comodo_api_username: 'likx2m7j'
comodo_api_password: 'Jimi13Kimi13'
authorize_net_key: '2s9n7LCP'
authorize_net_transaction_id: '27PD3Czbb343hY5R'
p_authorize_net_key: '3XzF96x5'
p_authorize_net_transaction_id: '473cmgtHDd7yY49K'

# 'local' for openssl, 'remote' to use java SOAP
csr_parser: local

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
featured_writer_label: 'Featured Writer'
allow_anonymous_commenting: false
require_captcha_on_signup: true
recaptcha_pub_key: 6Lch9QYAAAAAAMKfJMXiclR-6EuiZRBr8o98dHdF
recaptcha_priv_key: 6Lch9QYAAAAAAAlWpfQKWpn7eTkc3f2FWhv4fVIG
# uncomment these keys if you turn captcha on for commenting or signup
studio_fee_rate: .3
affiliate_cookie_days: 30
affiliate_program: "idevaffiliate"
cart_cookie_days: 30
reserved_logins: ['administrator', 'sysadmin', 'admin', 'support', 'sales', 'info', 'eroslife', 'systemadmin', 'moderator', 'operator']
exclude_amex: true
number_of_captured_frames: 20
max_content_size: 10
max_num_releases: 100
affiliate_param_key: 'code/r-'
thumbnail_tagline_size: 32
allow_reseller_validation: true
sync_aid_li_and_cart: false
browser_acceptance: "99.9%"
notify_address: "support@ssl.com"
disable_links_banner: false

from_email:
  orders: 'orders@ssl.com'
  activations: 'noreply@ssl.com'

photo:
  missing_micro: '/plugin_assets/community_engine/images/icon_missing_micro.gif'
  missing_thumb: '/plugin_assets/community_engine/images/icon_missing_thumb.gif'
  missing_medium: "/plugin_assets/community_engine/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "100x100!", medium: "290x320!", large: "664>", micro: "50x50!"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

feature:
  use_thumbs: true
  dimensions: [150, 635]
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    max_size: 1
    thumbnails: {thumb: '45x45!', large: '635x150!'}
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

clipping:
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    max_size: 3
    thumbnails: {thumb: "100x100!", medium_square: "200x200!", medium: "200>"}
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

theme: picclet