development:
  compile: true
  extract_css: false
  cache_manifest: false

test:
  compile: true
  extract_css: false
  cache_manifest: false

production:
  compile: false
  extract_css: true
  cache_manifest: true
