
# Preference.connection.truncate(Preference.table_name)
# Preference.create!([
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474120, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474120, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474120, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474120, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474120, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474121, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474121, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474121, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474121, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474121, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474122, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474122, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474122, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474122, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474122, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474123, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474123, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474123, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474123, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474123, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474124, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474124, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474124, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474124, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474124, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474125, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474125, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474125, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474125, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474125, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474126, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474126, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474126, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474126, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474126, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474127, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474127, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474127, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474127, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474127, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474128, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474128, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474128, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474128, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474128, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474129, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474129, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474129, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474129, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474129, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474130, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474130, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474130, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474130, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474130, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474131, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474131, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474131, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474131, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474131, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474132, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474132, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474132, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474132, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474132, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474133, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474133, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474133, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474133, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474133, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474134, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474134, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474134, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474134, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474134, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474135, owner_type: "SslAccount", group_id: 1, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474135, owner_type: "SslAccount", group_id: 2, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474135, owner_type: "SslAccount", group_id: 3, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474135, owner_type: "SslAccount", group_id: 4, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474135, owner_type: "SslAccount", group_id: 5, group_type: "ReminderTrigger", value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 6, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 7, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 8, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: 9, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474118, owner_type: "SslAccount", group_id: nil, group_type: nil, value: "-30"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 6, group_type: "ReminderTrigger", value: "60"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 7, group_type: "ReminderTrigger", value: "30"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 8, group_type: "ReminderTrigger", value: "7"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: 9, group_type: "ReminderTrigger", value: "1"},
#   {name: "reminder_notice_triggers", owner_id: 474119, owner_type: "SslAccount", group_id: nil, group_type: nil, value: "-30"}
# ])

Website.connection.truncate(Website.table_name)
Website.create!([
  {host: "sandbox.ssl.com", api_host: "sws-test.sslpki.com", name: "Production Sandbox Site", description: nil, type: "Sandbox", db_id: 1},
  {host: "sandbox2.ssl.com", api_host: "sws-test2.sslpki.com", name: "Development Sandbox Site", description: nil, type: "Sandbox", db_id: 1},
  {host: "sandbox.ssl.local", api_host: "sws-test.sslpki.local", name: "Production Sandbox Site", description: nil, type: "Sandbox", db_id: 1},
  {host: "sandbox2.ssl.local", api_host: "sws-test2.sslpki.local", name: "Development Sandbox Site", description: nil, type: "Sandbox", db_id: 1}
])

ServerSoftware.connection.truncate(ServerSoftware.table_name)
ServerSoftware.create!([
  {title: "OTHER", support_url: nil},
  {title: "AOL", support_url: nil},
  {title: "Apache-ModSSL", support_url: nil},
  {title: "Apache-SSL (Ben-SSL, not Stronghold)", support_url: nil},
  {title: "C2Net Stronghold", support_url: nil},
  {title: "Cisco 3000 Series VPN Concentrator", support_url: nil},
  {title: "Citrix", support_url: nil},
  {title: "Cobalt Raq", support_url: nil},
  {title: "Covalent Server Software", support_url: nil},
  {title: "Ensim", support_url: nil},
  {title: "HSphere", support_url: nil},
  {title: "IBM HTTP Server", support_url: nil},
  {title: "IBM Internet Connection Server", support_url: nil},
  {title: "iPlanet", support_url: nil},
  {title: "Java Web Server (Javasoft / Sun)", support_url: nil},
  {title: "Lotus Domino", support_url: nil},
  {title: "Lotus Domino Go!", support_url: nil},
  {title: "Microsoft IIS 1.x to 4.x", support_url: nil},
  {title: "Microsoft IIS 5.x to 6.x", support_url: nil},
  {title: "Microsoft IIS 7.x and later", support_url: nil},
  {title: "Netscape Enterprise Server", support_url: nil},
  {title: "Netscape FastTrack", support_url: nil},
  {title: "Novell Web Server", support_url: nil},
  {title: "Oracle", support_url: nil},
  {title: "Plesk", support_url: nil},
  {title: "Quid Pro Quo", support_url: nil},
  {title: "R3 SSL Server", support_url: nil},
  {title: "Raven SSL", support_url: nil},
  {title: "RedHat Linux", support_url: nil},
  {title: "SAP Web Application Server", support_url: nil},
  {title: "Tomcat", support_url: nil},
  {title: "Website Professional", support_url: nil},
  {title: "WebStar 4.x and later", support_url: nil},
  {title: "WebTen (from Tenon)", support_url: nil},
  {title: "WHM/CPanel", support_url: nil},
  {title: "Zeus Web Server", support_url: nil},
  {title: "Nginx", support_url: nil},
  {title: "Heroku", support_url: nil},
  {title: "Amazon Load Balancer", support_url: nil}
])

Country.connection.truncate(Country.table_name)
Country.create!([
  {iso1_code: "AG", name_caps: "ANTIGUA AND BARBUDA", name: "Antigua and Barbuda", iso3_code: "ATG", num_code: 28},
  {iso1_code: "ZA", name_caps: "SOUTH AFRICA", name: "South Africa", iso3_code: "ZAF", num_code: 710},
  {iso1_code: "TF", name_caps: "FRENCH SOUTHERN TERRITORIES", name: "French Southern Territories", iso3_code: nil, num_code: nil},
  {iso1_code: "KY", name_caps: "CAYMAN ISLANDS", name: "Cayman Islands", iso3_code: "CYM", num_code: 136},
  {iso1_code: "NC", name_caps: "NEW CALEDONIA", name: "New Caledonia", iso3_code: "NCL", num_code: 540},
  {iso1_code: "SN", name_caps: "SENEGAL", name: "Senegal", iso3_code: "SEN", num_code: 686},
  {iso1_code: "MR", name_caps: "MAURITANIA", name: "Mauritania", iso3_code: "MRT", num_code: 478},
  {iso1_code: "GL", name_caps: "GREENLAND", name: "Greenland", iso3_code: "GRL", num_code: 304},
  {iso1_code: "CU", name_caps: "CUBA", name: "Cuba", iso3_code: "CUB", num_code: 192},
  {iso1_code: "FO", name_caps: "FAROE ISLANDS", name: "Faroe Islands", iso3_code: "FRO", num_code: 234},
  {iso1_code: "BV", name_caps: "BOUVET ISLAND", name: "Bouvet Island", iso3_code: nil, num_code: nil},
  {iso1_code: "BA", name_caps: "BOSNIA AND HERZEGOVINA", name: "Bosnia and Herzegovina", iso3_code: "BIH", num_code: 70},
  {iso1_code: "VC", name_caps: "SAINT VINCENT AND THE GRENADINES", name: "Saint Vincent and the Grenadines", iso3_code: "VCT", num_code: 670},
  {iso1_code: "SY", name_caps: "SYRIAN ARAB REPUBLIC", name: "Syrian Arab Republic", iso3_code: "SYR", num_code: 760},
  {iso1_code: "JM", name_caps: "JAMAICA", name: "Jamaica", iso3_code: "JAM", num_code: 388},
  {iso1_code: "KN", name_caps: "SAINT KITTS AND NEVIS", name: "Saint Kitts and Nevis", iso3_code: "KNA", num_code: 659},
  {iso1_code: "PH", name_caps: "PHILIPPINES", name: "Philippines", iso3_code: "PHL", num_code: 608},
  {iso1_code: "DJ", name_caps: "DJIBOUTI", name: "Djibouti", iso3_code: "DJI", num_code: 262},
  {iso1_code: "PL", name_caps: "POLAND", name: "Poland", iso3_code: "POL", num_code: 616},
  {iso1_code: "NP", name_caps: "NEPAL", name: "Nepal", iso3_code: "NPL", num_code: 524},
  {iso1_code: "AT", name_caps: "AUSTRIA", name: "Austria", iso3_code: "AUT", num_code: 40},
  {iso1_code: "BE", name_caps: "BELGIUM", name: "Belgium", iso3_code: "BEL", num_code: 56},
  {iso1_code: "CF", name_caps: "CENTRAL AFRICAN REPUBLIC", name: "Central African Republic", iso3_code: "CAF", num_code: 140},
  {iso1_code: "VG", name_caps: "VIRGIN ISLANDS, BRITISH", name: "Virgin Islands, British", iso3_code: "VGB", num_code: 92},
  {iso1_code: "LB", name_caps: "LEBANON", name: "Lebanon", iso3_code: "LBN", num_code: 422},
  {iso1_code: "MA", name_caps: "MOROCCO", name: "Morocco", iso3_code: "MAR", num_code: 504},
  {iso1_code: "IO", name_caps: "BRITISH INDIAN OCEAN TERRITORY", name: "British Indian Ocean Territory", iso3_code: nil, num_code: nil},
  {iso1_code: "MV", name_caps: "MALDIVES", name: "Maldives", iso3_code: "MDV", num_code: 462},
  {iso1_code: "LU", name_caps: "LUXEMBOURG", name: "Luxembourg", iso3_code: "LUX", num_code: 442},
  {iso1_code: "WS", name_caps: "SAMOA", name: "Samoa", iso3_code: "WSM", num_code: 882},
  {iso1_code: "SJ", name_caps: "SVALBARD AND JAN MAYEN", name: "Svalbard and Jan Mayen", iso3_code: "SJM", num_code: 744},
  {iso1_code: "YT", name_caps: "MAYOTTE", name: "Mayotte", iso3_code: nil, num_code: nil},
  {iso1_code: "GH", name_caps: "GHANA", name: "Ghana", iso3_code: "GHA", num_code: 288},
  {iso1_code: "BR", name_caps: "BRAZIL", name: "Brazil", iso3_code: "BRA", num_code: 76},
  {iso1_code: "FK", name_caps: "FALKLAND ISLANDS (MALVINAS)", name: "Falkland Islands (Malvinas)", iso3_code: "FLK", num_code: 238},
  {iso1_code: "NG", name_caps: "NIGERIA", name: "Nigeria", iso3_code: "NGA", num_code: 566},
  {iso1_code: "UA", name_caps: "UKRAINE", name: "Ukraine", iso3_code: "UKR", num_code: 804},
  {iso1_code: "BZ", name_caps: "BELIZE", name: "Belize", iso3_code: "BLZ", num_code: 84},
  {iso1_code: "CY", name_caps: "CYPRUS", name: "Cyprus", iso3_code: "CYP", num_code: 196},
  {iso1_code: "SB", name_caps: "SOLOMON ISLANDS", name: "Solomon Islands", iso3_code: "SLB", num_code: 90},
  {iso1_code: "PS", name_caps: "PALESTINIAN TERRITORY, OCCUPIED", name: "Palestinian Territory, Occupied", iso3_code: "PSE", num_code: 275},
  {iso1_code: "TJ", name_caps: "TAJIKISTAN", name: "Tajikistan", iso3_code: "TJK", num_code: 762},
  {iso1_code: "NO", name_caps: "NORWAY", name: "Norway", iso3_code: "NOR", num_code: 578},
  {iso1_code: "ER", name_caps: "ERITREA", name: "Eritrea", iso3_code: "ERI", num_code: 232},
  {iso1_code: "ZM", name_caps: "ZAMBIA", name: "Zambia", iso3_code: "ZMB", num_code: 894},
  {iso1_code: "EE", name_caps: "ESTONIA", name: "Estonia", iso3_code: "EST", num_code: 233},
  {iso1_code: "CN", name_caps: "CHINA", name: "China", iso3_code: "CHN", num_code: 156},
  {iso1_code: "GW", name_caps: "GUINEA-BISSAU", name: "Guinea-Bissau", iso3_code: "GNB", num_code: 624},
  {iso1_code: "BM", name_caps: "BERMUDA", name: "Bermuda", iso3_code: "BMU", num_code: 60},
  {iso1_code: "MM", name_caps: "MYANMAR", name: "Myanmar", iso3_code: "MMR", num_code: 104},
  {iso1_code: "IT", name_caps: "ITALY", name: "Italy", iso3_code: "ITA", num_code: 380},
  {iso1_code: "GS", name_caps: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", name: "South Georgia and the South Sandwich Islands", iso3_code: nil, num_code: nil},
  {iso1_code: "BI", name_caps: "BURUNDI", name: "Burundi", iso3_code: "BDI", num_code: 108},
  {iso1_code: "UZ", name_caps: "UZBEKISTAN", name: "Uzbekistan", iso3_code: "UZB", num_code: 860},
  {iso1_code: "TN", name_caps: "TUNISIA", name: "Tunisia", iso3_code: "TUN", num_code: 788},
  {iso1_code: "PW", name_caps: "PALAU", name: "Palau", iso3_code: "PLW", num_code: 585},
  {iso1_code: "UM", name_caps: "UNITED STATES MINOR OUTLYING ISLANDS", name: "United States Minor Outlying Islands", iso3_code: nil, num_code: nil},
  {iso1_code: "AO", name_caps: "ANGOLA", name: "Angola", iso3_code: "AGO", num_code: 24},
  {iso1_code: "GD", name_caps: "GRENADA", name: "Grenada", iso3_code: "GRD", num_code: 308},
  {iso1_code: "LY", name_caps: "LIBYAN ARAB JAMAHIRIYA", name: "Libyan Arab Jamahiriya", iso3_code: "LBY", num_code: 434},
  {iso1_code: "MZ", name_caps: "MOZAMBIQUE", name: "Mozambique", iso3_code: "MOZ", num_code: 508},
  {iso1_code: "RE", name_caps: "REUNION", name: "Reunion", iso3_code: "REU", num_code: 638},
  {iso1_code: "NL", name_caps: "NETHERLANDS", name: "Netherlands", iso3_code: "NLD", num_code: 528},
  {iso1_code: "BY", name_caps: "BELARUS", name: "Belarus", iso3_code: "BLR", num_code: 112},
  {iso1_code: "CZ", name_caps: "CZECH REPUBLIC", name: "Czech Republic", iso3_code: "CZE", num_code: 203},
  {iso1_code: "SA", name_caps: "SAUDI ARABIA", name: "Saudi Arabia", iso3_code: "SAU", num_code: 682},
  {iso1_code: "ID", name_caps: "INDONESIA", name: "Indonesia", iso3_code: "IDN", num_code: 360},
  {iso1_code: "IS", name_caps: "ICELAND", name: "Iceland", iso3_code: "ISL", num_code: 352},
  {iso1_code: "LI", name_caps: "LIECHTENSTEIN", name: "Liechtenstein", iso3_code: "LIE", num_code: 438},
  {iso1_code: "SV", name_caps: "EL SALVADOR", name: "El Salvador", iso3_code: "SLV", num_code: 222},
  {iso1_code: "RU", name_caps: "RUSSIAN FEDERATION", name: "Russian Federation", iso3_code: "RUS", num_code: 643},
  {iso1_code: "CM", name_caps: "CAMEROON", name: "Cameroon", iso3_code: "CMR", num_code: 120},
  {iso1_code: "GT", name_caps: "GUATEMALA", name: "Guatemala", iso3_code: "GTM", num_code: 320},
  {iso1_code: "BN", name_caps: "BRUNEI DARUSSALAM", name: "Brunei Darussalam", iso3_code: "BRN", num_code: 96},
  {iso1_code: "DE", name_caps: "GERMANY", name: "Germany", iso3_code: "DEU", num_code: 276},
  {iso1_code: "PG", name_caps: "PAPUA NEW GUINEA", name: "Papua New Guinea", iso3_code: "PNG", num_code: 598},
  {iso1_code: "UY", name_caps: "URUGUAY", name: "Uruguay", iso3_code: "URY", num_code: 858},
  {iso1_code: "TZ", name_caps: "TANZANIA, UNITED REPUBLIC OF", name: "Tanzania, United Republic of", iso3_code: "TZA", num_code: 834},
  {iso1_code: "KE", name_caps: "KENYA", name: "Kenya", iso3_code: "KEN", num_code: 404},
  {iso1_code: "SR", name_caps: "SURINAME", name: "Suriname", iso3_code: "SUR", num_code: 740},
  {iso1_code: "MN", name_caps: "MONGOLIA", name: "Mongolia", iso3_code: "MNG", num_code: 496},
  {iso1_code: "HT", name_caps: "HAITI", name: "Haiti", iso3_code: "HTI", num_code: 332},
  {iso1_code: "GP", name_caps: "GUADELOUPE", name: "Guadeloupe", iso3_code: "GLP", num_code: 312},
  {iso1_code: "CI", name_caps: "COTE D'IVOIRE", name: "Cote D'Ivoire", iso3_code: "CIV", num_code: 384},
  {iso1_code: "BJ", name_caps: "BENIN", name: "Benin", iso3_code: "BEN", num_code: 204},
  {iso1_code: "MY", name_caps: "MALAYSIA", name: "Malaysia", iso3_code: "MYS", num_code: 458},
  {iso1_code: "SE", name_caps: "SWEDEN", name: "Sweden", iso3_code: "SWE", num_code: 752},
  {iso1_code: "KR", name_caps: "KOREA, REPUBLIC OF", name: "Korea, Republic of", iso3_code: "KOR", num_code: 410},
  {iso1_code: "TM", name_caps: "TURKMENISTAN", name: "Turkmenistan", iso3_code: "TKM", num_code: 795},
  {iso1_code: "PT", name_caps: "PORTUGAL", name: "Portugal", iso3_code: "PRT", num_code: 620},
  {iso1_code: "AL", name_caps: "ALBANIA", name: "Albania", iso3_code: "ALB", num_code: 8},
  {iso1_code: "SM", name_caps: "SAN MARINO", name: "San Marino", iso3_code: "SMR", num_code: 674},
  {iso1_code: "MQ", name_caps: "MARTINIQUE", name: "Martinique", iso3_code: "MTQ", num_code: 474},
  {iso1_code: "LR", name_caps: "LIBERIA", name: "Liberia", iso3_code: "LBR", num_code: 430},
  {iso1_code: "HK", name_caps: "HONG KONG", name: "Hong Kong", iso3_code: "HKG", num_code: 344},
  {iso1_code: "CV", name_caps: "CAPE VERDE", name: "Cape Verde", iso3_code: "CPV", num_code: 132},
  {iso1_code: "AD", name_caps: "ANDORRA", name: "Andorra", iso3_code: "AND", num_code: 20},
  {iso1_code: "KZ", name_caps: "KAZAKHSTAN", name: "Kazakhstan", iso3_code: "KAZ", num_code: 398},
  {iso1_code: "KM", name_caps: "COMOROS", name: "Comoros", iso3_code: "COM", num_code: 174},
  {iso1_code: "TR", name_caps: "TURKEY", name: "Turkey", iso3_code: "TUR", num_code: 792},
  {iso1_code: "PK", name_caps: "PAKISTAN", name: "Pakistan", iso3_code: "PAK", num_code: 586},
  {iso1_code: "AS", name_caps: "AMERICAN SAMOA", name: "American Samoa", iso3_code: "ASM", num_code: 16},
  {iso1_code: "BB", name_caps: "BARBADOS", name: "Barbados", iso3_code: "BRB", num_code: 52},
  {iso1_code: "CA", name_caps: "CANADA", name: "Canada", iso3_code: "CAN", num_code: 124},
  {iso1_code: "SZ", name_caps: "SWAZILAND", name: "Swaziland", iso3_code: "SWZ", num_code: 748},
  {iso1_code: "BF", name_caps: "BURKINA FASO", name: "Burkina Faso", iso3_code: "BFA", num_code: 854},
  {iso1_code: "LA", name_caps: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", name: "Lao People's Democratic Republic", iso3_code: "LAO", num_code: 418},
  {iso1_code: "TV", name_caps: "TUVALU", name: "Tuvalu", iso3_code: "TUV", num_code: 798},
  {iso1_code: "KI", name_caps: "KIRIBATI", name: "Kiribati", iso3_code: "KIR", num_code: 296},
  {iso1_code: "DM", name_caps: "DOMINICA", name: "Dominica", iso3_code: "DMA", num_code: 212},
  {iso1_code: "AW", name_caps: "ARUBA", name: "Aruba", iso3_code: "ABW", num_code: 533},
  {iso1_code: "DZ", name_caps: "ALGERIA", name: "Algeria", iso3_code: "DZA", num_code: 12},
  {iso1_code: "IL", name_caps: "ISRAEL", name: "Israel", iso3_code: "ISR", num_code: 376},
  {iso1_code: "MU", name_caps: "MAURITIUS", name: "Mauritius", iso3_code: "MUS", num_code: 480},
  {iso1_code: "LV", name_caps: "LATVIA", name: "Latvia", iso3_code: "LVA", num_code: 428},
  {iso1_code: "SI", name_caps: "SLOVENIA", name: "Slovenia", iso3_code: "SVN", num_code: 705},
  {iso1_code: "CR", name_caps: "COSTA RICA", name: "Costa Rica", iso3_code: "CRI", num_code: 188},
  {iso1_code: "NI", name_caps: "NICARAGUA", name: "Nicaragua", iso3_code: "NIC", num_code: 558},
  {iso1_code: "JP", name_caps: "JAPAN", name: "Japan", iso3_code: "JPN", num_code: 392},
  {iso1_code: "ET", name_caps: "ETHIOPIA", name: "Ethiopia", iso3_code: "ETH", num_code: 231},
  {iso1_code: "AM", name_caps: "ARMENIA", name: "Armenia", iso3_code: "ARM", num_code: 51},
  {iso1_code: "GF", name_caps: "FRENCH GUIANA", name: "French Guiana", iso3_code: "GUF", num_code: 254},
  {iso1_code: "MX", name_caps: "MEXICO", name: "Mexico", iso3_code: "MEX", num_code: 484},
  {iso1_code: "SD", name_caps: "SUDAN", name: "Sudan", iso3_code: "SDN", num_code: 729},
  {iso1_code: "VI", name_caps: "VIRGIN ISLANDS, U.S.", name: "Virgin Islands, U.s.", iso3_code: "VIR", num_code: 0},
  {iso1_code: "MO", name_caps: "MACAO", name: "Macao", iso3_code: "MAC", num_code: 446},
  {iso1_code: "HU", name_caps: "HUNGARY", name: "Hungary", iso3_code: "HUN", num_code: 348},
  {iso1_code: "CH", name_caps: "SWITZERLAND", name: "Switzerland", iso3_code: "CHE", num_code: 756},
  {iso1_code: "GQ", name_caps: "EQUATORIAL GUINEA", name: "Equatorial Guinea", iso3_code: "GNQ", num_code: 226},
  {iso1_code: "FR", name_caps: "FRANCE", name: "France", iso3_code: "FRA", num_code: 250},
  {iso1_code: "EC", name_caps: "ECUADOR", name: "Ecuador", iso3_code: "ECU", num_code: 218},
  {iso1_code: "AZ", name_caps: "AZERBAIJAN", name: "Azerbaijan", iso3_code: "AZE", num_code: 31},
  {iso1_code: "QA", name_caps: "QATAR", name: "Qatar", iso3_code: "QAT", num_code: 634},
  {iso1_code: "EG", name_caps: "EGYPT", name: "Egypt", iso3_code: "EGY", num_code: 818},
  {iso1_code: "NZ", name_caps: "NEW ZEALAND", name: "New Zealand", iso3_code: "NZL", num_code: 554},
  {iso1_code: "PF", name_caps: "FRENCH POLYNESIA", name: "French Polynesia", iso3_code: "PYF", num_code: 258},
  {iso1_code: "MK", name_caps: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", name: "Macedonia, the Former Yugoslav Republic of", iso3_code: "MKD", num_code: 807},
  {iso1_code: "IR", name_caps: "IRAN, ISLAMIC REPUBLIC OF", name: "Iran, Islamic Republic of", iso3_code: "IRN", num_code: 364},
  {iso1_code: "GU", name_caps: "GUAM", name: "Guam", iso3_code: "GUM", num_code: 316},
  {iso1_code: "CL", name_caps: "CHILE", name: "Chile", iso3_code: "CHL", num_code: 152},
  {iso1_code: "BO", name_caps: "BOLIVIA", name: "Bolivia, Plurinational State of", iso3_code: "BOL", num_code: 68},
  {iso1_code: "GB", name_caps: "UNITED KINGDOM", name: "United Kingdom", iso3_code: "GBR", num_code: 826},
  {iso1_code: "IE", name_caps: "IRELAND", name: "Ireland", iso3_code: "IRL", num_code: 372},
  {iso1_code: "TH", name_caps: "THAILAND", name: "Thailand", iso3_code: "THA", num_code: 764},
  {iso1_code: "KW", name_caps: "KUWAIT", name: "Kuwait", iso3_code: "KWT", num_code: 414},
  {iso1_code: "AI", name_caps: "ANGUILLA", name: "Anguilla", iso3_code: "AIA", num_code: 660},
  {iso1_code: "MT", name_caps: "MALTA", name: "Malta", iso3_code: "MLT", num_code: 470},
  {iso1_code: "HN", name_caps: "HONDURAS", name: "Honduras", iso3_code: "HND", num_code: 340},
  {iso1_code: "SH", name_caps: "SAINT HELENA", name: "Saint Helena", iso3_code: "SHN", num_code: 654},
  {iso1_code: "FI", name_caps: "FINLAND", name: "Finland", iso3_code: "FIN", num_code: 246},
  {iso1_code: "NE", name_caps: "NIGER", name: "Niger", iso3_code: "NER", num_code: 562},
  {iso1_code: "PY", name_caps: "PARAGUAY", name: "Paraguay", iso3_code: "PRY", num_code: 600},
  {iso1_code: "TW", name_caps: "TAIWAN, PROVINCE OF CHINA", name: "Taiwan, Province of China", iso3_code: "TWN", num_code: 158},
  {iso1_code: "PN", name_caps: "PITCAIRN", name: "Pitcairn", iso3_code: "PCN", num_code: 612},
  {iso1_code: "NR", name_caps: "NAURU", name: "Nauru", iso3_code: "NRU", num_code: 520},
  {iso1_code: "KH", name_caps: "CAMBODIA", name: "Cambodia", iso3_code: "KHM", num_code: 116},
  {iso1_code: "BG", name_caps: "BULGARIA", name: "Bulgaria", iso3_code: "BGR", num_code: 100},
  {iso1_code: "CD", name_caps: "CONGO, THE DEMOCRATIC REPUBLIC OF THE", name: "Congo, the Democratic Republic of the", iso3_code: "COD", num_code: 180},
  {iso1_code: "VE", name_caps: "VENEZUELA", name: "Venezuela", iso3_code: "VEN", num_code: 862},
  {iso1_code: "WF", name_caps: "WALLIS AND FUTUNA", name: "Wallis and Futuna", iso3_code: "WLF", num_code: 876},
  {iso1_code: "MC", name_caps: "MONACO", name: "Monaco", iso3_code: "MCO", num_code: 492},
  {iso1_code: "YE", name_caps: "YEMEN", name: "Yemen", iso3_code: "YEM", num_code: 887},
  {iso1_code: "GY", name_caps: "GUYANA", name: "Guyana", iso3_code: "GUY", num_code: 328},
  {iso1_code: "MG", name_caps: "MADAGASCAR", name: "Madagascar", iso3_code: "MDG", num_code: 450},
  {iso1_code: "VA", name_caps: "HOLY SEE (VATICAN CITY STATE)", name: "Holy See (Vatican City State)", iso3_code: "VAT", num_code: 336},
  {iso1_code: "JO", name_caps: "JORDAN", name: "Jordan", iso3_code: "JOR", num_code: 400},
  {iso1_code: "AR", name_caps: "ARGENTINA", name: "Argentina", iso3_code: "ARG", num_code: 32},
  {iso1_code: "AE", name_caps: "UNITED ARAB EMIRATES", name: "United Arab Emirates", iso3_code: "ARE", num_code: 784},
  {iso1_code: "UG", name_caps: "UGANDA", name: "Uganda", iso3_code: "UGA", num_code: 800},
  {iso1_code: "TD", name_caps: "CHAD", name: "Chad", iso3_code: "TCD", num_code: 148},
  {iso1_code: "NA", name_caps: "NAMIBIA", name: "Namibia", iso3_code: "NAM", num_code: 516},
  {iso1_code: "SL", name_caps: "SIERRA LEONE", name: "Sierra Leone", iso3_code: "SLE", num_code: 694},
  {iso1_code: "RO", name_caps: "ROMANIA", name: "Romania", iso3_code: "ROU", num_code: 642},
  {iso1_code: "MP", name_caps: "NORTHERN MARIANA ISLANDS", name: "Northern Mariana Islands", iso3_code: "MNP", num_code: 580},
  {iso1_code: "LS", name_caps: "LESOTHO", name: "Lesotho", iso3_code: "LSO", num_code: 426},
  {iso1_code: "GN", name_caps: "GUINEA", name: "Guinea", iso3_code: "GIN", num_code: 324},
  {iso1_code: "BT", name_caps: "BHUTAN", name: "Bhutan", iso3_code: "BTN", num_code: 64},
  {iso1_code: "FM", name_caps: "MICRONESIA, FEDERATED STATES OF", name: "Micronesia, Federated States of", iso3_code: "FSM", num_code: 583},
  {iso1_code: "NF", name_caps: "NORFOLK ISLAND", name: "Norfolk Island", iso3_code: "NFK", num_code: 574},
  {iso1_code: "TC", name_caps: "TURKS AND CAICOS ISLANDS", name: "Turks and Caicos Islands", iso3_code: "TCA", num_code: 796},
  {iso1_code: "MW", name_caps: "MALAWI", name: "Malawi", iso3_code: "MWI", num_code: 454},
  {iso1_code: "IN", name_caps: "INDIA", name: "India", iso3_code: "IND", num_code: 356},
  {iso1_code: "LT", name_caps: "LITHUANIA", name: "Lithuania", iso3_code: "LTU", num_code: 440},
  {iso1_code: "HM", name_caps: "HEARD ISLAND AND MCDONALD ISLANDS", name: "Heard Island and Mcdonald Islands", iso3_code: nil, num_code: nil},
  {iso1_code: "SK", name_caps: "SLOVAKIA", name: "Slovakia", iso3_code: "SVK", num_code: 703},
  {iso1_code: "GI", name_caps: "GIBRALTAR", name: "Gibraltar", iso3_code: "GIB", num_code: 292},
  {iso1_code: "FJ", name_caps: "FIJI", name: "Fiji", iso3_code: "FJI", num_code: 242},
  {iso1_code: "BS", name_caps: "BAHAMAS", name: "Bahamas", iso3_code: "BHS", num_code: 44},
  {iso1_code: "BD", name_caps: "BANGLADESH", name: "Bangladesh", iso3_code: "BGD", num_code: 50},
  {iso1_code: "CG", name_caps: "CONGO", name: "Congo", iso3_code: "COG", num_code: 178},
  {iso1_code: "LC", name_caps: "SAINT LUCIA", name: "Saint Lucia", iso3_code: "LCA", num_code: 662},
  {iso1_code: "TT", name_caps: "TRINIDAD AND TOBAGO", name: "Trinidad and Tobago", iso3_code: "TTO", num_code: 780},
  {iso1_code: "PM", name_caps: "SAINT PIERRE AND MIQUELON", name: "Saint Pierre and Miquelon", iso3_code: "SPM", num_code: 666},
  {iso1_code: "DO", name_caps: "DOMINICAN REPUBLIC", name: "Dominican Republic", iso3_code: "DOM", num_code: 214},
  {iso1_code: "AU", name_caps: "AUSTRALIA", name: "Australia", iso3_code: "AUS", num_code: 36},
  {iso1_code: "NU", name_caps: "NIUE", name: "Niue", iso3_code: "NIU", num_code: 570},
  {iso1_code: "US", name_caps: "UNITED STATES", name: "United States", iso3_code: "USA", num_code: 840},
  {iso1_code: "ZW", name_caps: "ZIMBABWE", name: "Zimbabwe", iso3_code: "ZWE", num_code: 716},
  {iso1_code: "DK", name_caps: "DENMARK", name: "Denmark", iso3_code: "DNK", num_code: 208},
  {iso1_code: "EH", name_caps: "WESTERN SAHARA", name: "Western Sahara", iso3_code: "ESH", num_code: 732},
  {iso1_code: "AQ", name_caps: "ANTARCTICA", name: "Antarctica", iso3_code: nil, num_code: nil},
  {iso1_code: "CC", name_caps: "COCOS (KEELING) ISLANDS", name: "Cocos (Keeling) Islands", iso3_code: nil, num_code: nil},
  {iso1_code: "MD", name_caps: "MOLDOVA, REPUBLIC OF", name: "Moldova, Republic of", iso3_code: "MDA", num_code: 498},
  {iso1_code: "SO", name_caps: "SOMALIA", name: "Somalia", iso3_code: "SOM", num_code: 706},
  {iso1_code: "VU", name_caps: "VANUATU", name: "Vanuatu", iso3_code: "VUT", num_code: 548},
  {iso1_code: "MS", name_caps: "MONTSERRAT", name: "Montserrat", iso3_code: "MSR", num_code: 500},
  {iso1_code: "GM", name_caps: "GAMBIA", name: "Gambia", iso3_code: "GMB", num_code: 270},
  {iso1_code: "BW", name_caps: "BOTSWANA", name: "Botswana", iso3_code: "BWA", num_code: 72},
  {iso1_code: "AF", name_caps: "AFGHANISTAN", name: "Afghanistan", iso3_code: "AFG", num_code: 4},
  {iso1_code: "TG", name_caps: "TOGO", name: "Togo", iso3_code: "TGO", num_code: 768},
  {iso1_code: "GE", name_caps: "GEORGIA", name: "Georgia", iso3_code: "GEO", num_code: 268},
  {iso1_code: "SG", name_caps: "SINGAPORE", name: "Singapore", iso3_code: "SGP", num_code: 702},
  {iso1_code: "KP", name_caps: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", name: "Korea, Democratic People's Republic of", iso3_code: "PRK", num_code: 408},
  {iso1_code: "TO", name_caps: "TONGA", name: "Tonga", iso3_code: "TON", num_code: 776},
  {iso1_code: "AN", name_caps: "NETHERLANDS ANTILLES", name: "Netherlands Antilles", iso3_code: "ANT", num_code: 530},
  {iso1_code: "PA", name_caps: "PANAMA", name: "Panama", iso3_code: "PAN", num_code: 591},
  {iso1_code: "KG", name_caps: "KYRGYZSTAN", name: "Kyrgyzstan", iso3_code: "KGZ", num_code: 417},
  {iso1_code: "ML", name_caps: "MALI", name: "Mali", iso3_code: "MLI", num_code: 466},
  {iso1_code: "CK", name_caps: "COOK ISLANDS", name: "Cook Islands", iso3_code: "COK", num_code: 184},
  {iso1_code: "GR", name_caps: "GREECE", name: "Greece", iso3_code: "GRC", num_code: 300},
  {iso1_code: "BH", name_caps: "BAHRAIN", name: "Bahrain", iso3_code: "BHR", num_code: 48},
  {iso1_code: "MH", name_caps: "MARSHALL ISLANDS", name: "Marshall Islands", iso3_code: "MHL", num_code: 584},
  {iso1_code: "IQ", name_caps: "IRAQ", name: "Iraq", iso3_code: "IRQ", num_code: 368},
  {iso1_code: "LK", name_caps: "SRI LANKA", name: "Sri Lanka", iso3_code: "LKA", num_code: 144},
  {iso1_code: "HR", name_caps: "CROATIA", name: "Croatia", iso3_code: "HRV", num_code: 191},
  {iso1_code: "ST", name_caps: "SAO TOME AND PRINCIPE", name: "Sao Tome and Principe", iso3_code: "STP", num_code: 678},
  {iso1_code: "RW", name_caps: "RWANDA", name: "Rwanda", iso3_code: "RWA", num_code: 646},
  {iso1_code: "VN", name_caps: "VIET NAM", name: "Viet Nam", iso3_code: "VNM", num_code: 704},
  {iso1_code: "CO", name_caps: "COLOMBIA", name: "Colombia", iso3_code: "COL", num_code: 170},
  {iso1_code: "PE", name_caps: "PERU", name: "Peru", iso3_code: "PER", num_code: 604},
  {iso1_code: "TK", name_caps: "TOKELAU", name: "Tokelau", iso3_code: "TKL", num_code: 772},
  {iso1_code: "PR", name_caps: "PUERTO RICO", name: "Puerto Rico", iso3_code: "PRI", num_code: 630},
  {iso1_code: "OM", name_caps: "OMAN", name: "Oman", iso3_code: "OMN", num_code: 512},
  {iso1_code: "ES", name_caps: "SPAIN", name: "Spain", iso3_code: "ESP", num_code: 724},
  {iso1_code: "GA", name_caps: "GABON", name: "Gabon", iso3_code: "GAB", num_code: 266},
  {iso1_code: "CX", name_caps: "CHRISTMAS ISLAND", name: "Christmas Island", iso3_code: nil, num_code: nil},
  {iso1_code: "SC", name_caps: "SEYCHELLES", name: "Seychelles", iso3_code: "SYC", num_code: 690},
  {iso1_code: "ME", name_caps: "MONTENEGRO", name: "Montenegro", iso3_code: "MNE", num_code: 499},
  {iso1_code: "RS", name_caps: "SERBIA", name: "Serbia", iso3_code: "SRB", num_code: 688},
  {iso1_code: "JE", name_caps: "JERSEY", name: "Jersey", iso3_code: "JEY", num_code: 832},
  {iso1_code: "IM", name_caps: "ISLE OF MAN", name: "Isle of Man", iso3_code: "IMN", num_code: 833},
  {iso1_code: "GG", name_caps: "GUERNSEY", name: "Guernsey", iso3_code: "GGY", num_code: 831},
  {iso1_code: "AX", name_caps: "ALAND ISLANDS", name: "Aland Islands", iso3_code: "ALA", num_code: 248},
  {iso1_code: "TL", name_caps: "TIMOR-LESTE", name: "Timor-Leste", iso3_code: "TLS", num_code: 626},
  {iso1_code: "TL", name_caps: "SINT MAARTEN (DUTCH PART)", name: "Sint Maarten (Dutch part)", iso3_code: "SXM", num_code: 534},
  {iso1_code: "SS", name_caps: "SOUTH SUDAN", name: "South Sudan", iso3_code: "SSD", num_code: 728},
  {iso1_code: "BQ", name_caps: "BONAIRE, SINT EUSTATIUS AND SABA", name: "Bonaire, Sint Eustatius and Saba", iso3_code: "BES", num_code: 535},
  {iso1_code: "CW", name_caps: "CURACAO", name: "Curacao", iso3_code: "CUW", num_code: 531}
])

Ca.destroy_all
Ca.create!([
  {"id"=>1, "ref"=>"0", "friendly_name"=>"SSL.com Shadow", "profile_name"=>"Management CA", "algorithm"=>"rsa", "size"=>nil, "description"=>"SSL.com Shadow", "caa_issuers"=>nil, "host"=>nil, "admin_host"=>nil, "ekus"=>nil, "end_entity"=>nil, "ca_name"=>nil, "type"=>nil, "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>2, "ref"=>"1000", "friendly_name"=>"CertLock SSL RSA 4096 (EV,", "profile_name"=>"CertLock-SubCA-EV-SSL-RSA-4096", "algorithm"=>"rsa", "size"=>4096, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"EV_SERVER_CERT_EE", "ca_name"=>"certlock", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>3, "ref"=>"1001", "friendly_name"=>"CertLock SSL RSA 4096 (DV,", "profile_name"=>"CertLock-SubCA-SSL-RSA-4096", "algorithm"=>"rsa", "size"=>4096, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"DV_SERVER_CERT_EE", "ca_name"=>"certlock", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>4, "ref"=>"1002", "friendly_name"=>"CertLock SSL RSA 4096 (OV,", "profile_name"=>"CertLock-SubCA-SSL-RSA-4096", "algorithm"=>"rsa", "size"=>4096, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"OV_SERVER_CERT_EE", "ca_name"=>"certlock", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>5, "ref"=>"1003", "friendly_name"=>"CertLock SSL ECC (DV,", "profile_name"=>"CertLockECCSSLsubCA", "algorithm"=>"ecc", "size"=>384, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"DV_SERVER_CERT_EE", "ca_name"=>"certlock", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>6, "ref"=>"1004", "friendly_name"=>"CertLock SSL ECC (OV,", "profile_name"=>"CertLockECCSSLsubCA", "algorithm"=>"ecc", "size"=>384, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"OV_SERVER_CERT_EE", "ca_name"=>"certlock", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>7, "ref"=>"1005", "friendly_name"=>"CertLock SSL ECC (EV,", "profile_name"=>"CertLockEVECCSSLsubCA", "algorithm"=>"ecc", "size"=>384, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"EV_SERVER_CERT_EE", "ca_name"=>"certlock", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>8, "ref"=>"1006", "friendly_name"=>"CertLockEVROOTCAECC", "profile_name"=>"CertLockEVROOTCAECC", "algorithm"=>"ecc", "size"=>384, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"certlock", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>9, "ref"=>"1007", "friendly_name"=>"CertLockEVROOTCARSA", "profile_name"=>"CertLockEVROOTCARSA", "algorithm"=>"rsa", "size"=>4096, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"certlock", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>10, "ref"=>"1008", "friendly_name"=>"CertLockROOTCAECC", "profile_name"=>"CertLockROOTCAECC", "algorithm"=>"ecc", "size"=>384, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"certlock", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>11, "ref"=>"1009", "friendly_name"=>"CertLockROOTCARSA", "profile_name"=>"CertLockROOTCARSA", "algorithm"=>"rsa", "size"=>4096, "description"=>"certlock", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"certlock", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>12, "ref"=>"1100", "friendly_name"=>"ECOsslcom-RootCA-ECC-384-R1", "profile_name"=>"ECOsslcom-RootCA-ECC-384-R1", "algorithm"=>"ecc", "size"=>384, "description"=>"ecossl", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"ecossl", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>13, "ref"=>"1101", "friendly_name"=>"ECOsslcom-RootCA-RSA-4096-R1", "profile_name"=>"ECOsslcom-RootCA-RSA-4096-R1", "algorithm"=>"rsa", "size"=>4096, "description"=>"ecossl", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"ecossl", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>14, "ref"=>"1200", "friendly_name"=>"ManagementCA", "profile_name"=>"ManagementCA", "algorithm"=>"rsa", "size"=>4096, "description"=>"", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"management_ca", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>15, "ref"=>"0001", "friendly_name"=>"SSL.com EV CS RSA 4096", "profile_name"=>"EV_RSA_CS_ULMT_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>"cs", "end_entity"=>"EV_CS_CERT_EE", "ca_name"=>"SSL.com-EV-codeSigning-Intermediate-RSA-4096", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>16, "ref"=>"0002", "friendly_name"=>"SSLcom-RootCA-ECC-384-R1", "profile_name"=>"SSLcom-RootCA-ECC-384-R1", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>17, "ref"=>"0003", "friendly_name"=>"SSLcom-RootCA-ECC-384-R2", "profile_name"=>"SSLcom-RootCA-ECC-384-R2", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>18, "ref"=>"0004", "friendly_name"=>"SSLcom-RootCA-EV-ECC-384-R1", "profile_name"=>"SSLcom-RootCA-EV-ECC-384-R1", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>19, "ref"=>"0005", "friendly_name"=>"SSLcom-RootCA-EV-ECC-384-R2", "profile_name"=>"SSLcom-RootCA-EV-ECC-384-R2", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>20, "ref"=>"0006", "friendly_name"=>"SSL.com SSL ECC 384 (EV,", "profile_name"=>"EV_ECC_SERVER_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"EV_SERVER_CERT_EE", "ca_name"=>"SSLcom-SubCA-EV-SSL-ECC-384-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>21, "ref"=>"0007", "friendly_name"=>"SSL.com SSL ECC 384 (DV,", "profile_name"=>"DV_ECC_SERVER_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"DV_SERVER_CERT_EE", "ca_name"=>"SSLcom-SubCA-SSL-ECC-384-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>22, "ref"=>"0008", "friendly_name"=>"SSL.com SSL ECC 384 (OV,", "profile_name"=>"OV_ECC_SERVER_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"OV_SERVER_CERT_EE", "ca_name"=>"SSLcom-SubCA-SSL-ECC-384-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>23, "ref"=>"0009", "friendly_name"=>"SSLcom-RootCA-EV-RSA-4096-R2", "profile_name"=>"SSLcom-RootCA-EV-RSA-4096-R2", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>24, "ref"=>"0010", "friendly_name"=>"SSLcom-RootCA-EV-RSA-4096-R3", "profile_name"=>"SSLcom-RootCA-EV-RSA-4096-R3", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>25, "ref"=>"0011", "friendly_name"=>"SSLcom-RootCA-RSA-4096-R1", "profile_name"=>"SSLcom-RootCA-RSA-4096-R1", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>26, "ref"=>"0012", "friendly_name"=>"SSLcom-RootCA-RSA-4096-R2", "profile_name"=>"SSLcom-RootCA-RSA-4096-R2", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>27, "ref"=>"0013", "friendly_name"=>"SSL.com CS RSA 4096", "profile_name"=>"RSA_CS_ULMT_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["cs"], "end_entity"=>"CS_CERT_EE", "ca_name"=>"SSLcom-SubCA-CodeSigning-RSA-4096-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>28, "ref"=>"0014", "friendly_name"=>"SSL.com EV CS RSA 4096 R2", "profile_name"=>"EV_RSA_CS_ULMT_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["cs"], "end_entity"=>"EV_CS_CERT_EE", "ca_name"=>"SSLcom-SubCA-EV-CodeSigning-RSA-4096-R3", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>29, "ref"=>"0015", "friendly_name"=>"SSL.com SSL RSA 4096 R3 (EV,", "profile_name"=>"EV_RSA_SERVER_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"EV_SERVER_CERT_EE", "ca_name"=>"SSLcom-SubCA-EV-SSL-RSA-4096-R3", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>30, "ref"=>"0016", "friendly_name"=>"SSL.com EV TimeStamping RSA 4096", "profile_name"=>"SSLcom-SubCA-EV-TimeStamping-RSA-4096-R1", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["ts"], "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>31, "ref"=>"0017", "friendly_name"=>"SSL.com SSL RSA 4096 (DV,", "profile_name"=>"DV_RSA_SERVER_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"DV_SERVER_CERT_EE", "ca_name"=>"SSLcom-SubCA-SSL-RSA-4096-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>32, "ref"=>"0018", "friendly_name"=>"SSL.com SSL RSA 4096 (OV,", "profile_name"=>"OV_RSA_SERVER_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"OV_SERVER_CERT_EE", "ca_name"=>"SSLcom-SubCA-SSL-RSA-4096-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>33, "ref"=>"0019", "friendly_name"=>"SSLcomEVROOTCARSA", "profile_name"=>"SSLcomEVROOTCARSA", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>nil, "end_entity"=>nil, "ca_name"=>"sslcom", "type"=>"RootCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>34, "ref"=>"0020", "friendly_name"=>"SSLcomEVRSASSLsubCA", "profile_name"=>"EV_RSA_SERVER_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["tls"], "end_entity"=>"EV_SERVER_CERT_EE", "ca_name"=>"SSLcom-SubCA-EV-SSL-RSA-4096-R3", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>35, "ref"=>"0021", "friendly_name"=>"NAESB Client Cert Rudimentary Assurance RSA", "profile_name"=>"RSA_NAESB_RA_CLIENT_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-RSA-4096-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>36, "ref"=>"0022", "friendly_name"=>"NAESB Client Cert Basic Assurance RSA", "profile_name"=>"RSA_NAESB_BA_CLIENT_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-RSA-4096-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>37, "ref"=>"0023", "friendly_name"=>"NAESB Client Cert High Assurance RSA", "profile_name"=>"RSA_NAESB_HA_CLIENT_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-RSA-4096-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>38, "ref"=>"0024", "friendly_name"=>"NAESB Client Cert Medium Assurance RSA", "profile_name"=>"RSA_NAESB_MA_CLIENT_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-RSA-4096-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>39, "ref"=>"0025", "friendly_name"=>"NAESB Client Cert Rudimentary Assurance ECC", "profile_name"=>"OV_ECC_NAESB_RA_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-ECC-384-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>40, "ref"=>"0026", "friendly_name"=>"NAESB Client Cert Basic Assurance ECC", "profile_name"=>"OV_ECC_NAESB_BA_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-ECC-384-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>41, "ref"=>"0027", "friendly_name"=>"NAESB Client Cert High Assurance ECC", "profile_name"=>"OV_ECC_NAESB_HA_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-ECC-384-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>42, "ref"=>"0028", "friendly_name"=>"NAESB RSA Client Cert Medium Assurance ECC", "profile_name"=>"OV_ECC_NAESB_MA_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"OV_CLIENTAUTH_CERT_EE", "ca_name"=>"SSLcom-SubCA-NAESB-clientAuth-ECC-384-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>43, "ref"=>"0030", "friendly_name"=>"SSL.com CS ECC 384", "profile_name"=>"ECC_CS_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["cs"], "end_entity"=>"CS_CERT_EE", "ca_name"=>"SSLcom-SubCA-CodeSigning-ECC-384-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>44, "ref"=>"0031", "friendly_name"=>"SSL.com EV CS ECC 384 R1", "profile_name"=>"EV_ECC_CS_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["cs"], "end_entity"=>"EV_CS_CERT_EE", "ca_name"=>"SSLcom-SubCA-EV-CodeSigning-ECC-384-R1", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>45, "ref"=>"0032", "friendly_name"=>"SSL.com Basic Email RSA", "profile_name"=>"MYSSL_EAV_RSA_SMIME_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"MYSSL_EAV_CERT_EE", "ca_name"=>"SSLcom-SubCA-clientCert-RSA-4096-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>46, "ref"=>"0033", "friendly_name"=>"SSL.com MySSL Pro RSA", "profile_name"=>"MYSSL_IV_RSA_SMIME_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"MYSSL_IV_CERT_EE", "ca_name"=>"SSLcom-SubCA-clientCert-RSA-4096-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>47, "ref"=>"0034", "friendly_name"=>"SSL.com Basic Email ECC", "profile_name"=>"MYSSL_EAV_ECC_SMIME_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"MYSSL_EAV_CERT_EE", "ca_name"=>"SSLcom-SubCA-clientCert-ECC-384-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>48, "ref"=>"0035", "friendly_name"=>"SSL.com MySSL Pro ECC", "profile_name"=>"MYSSL_IV_ECC_SMIME_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"MYSSL_IV_CERT_EE", "ca_name"=>"SSLcom-SubCA-clientCert-ECC-384-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>49, "ref"=>"0036", "friendly_name"=>"SSL.com Business Identity RSA", "profile_name"=>"MYSSL_OV_RSA_SMIME_DOCSIGNING_CERT", "algorithm"=>"rsa", "size"=>4096, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"MYSSL_OV_CERT_EE", "ca_name"=>"SSLcom-SubCA-clientCert-RSA-4096-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>50, "ref"=>"0037", "friendly_name"=>"SSL.com Business Identity ECC", "profile_name"=>"MYSSL_OV_ECC_SMIME_DOCSIGNING_CERT", "algorithm"=>"ecc", "size"=>384, "description"=>"sslcom", "caa_issuers"=>["ssl.com"], "host"=>"https://calypso-dev-01.int.ssl.com:8443/restapi", "admin_host"=>"https://192.168.100.5:8443", "ekus"=>["client"], "end_entity"=>"MYSSL_OV_CERT_EE", "ca_name"=>"SSLcom-SubCA-clientCert-ECC-384-R2", "type"=>"SubCa", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>51, "ref"=>"3000", "friendly_name"=>"DV_SERVER_CERT_EE", "profile_name"=>"DV_SERVER_CERT_EE", "algorithm"=>"", "size"=>4096, "description"=>"", "caa_issuers"=>nil, "host"=>nil, "admin_host"=>nil, "ekus"=>nil, "end_entity"=>nil, "ca_name"=>nil, "type"=>"EndEntityProfile", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>52, "ref"=>"3001", "friendly_name"=>"OV_SERVER_CERT_EE", "profile_name"=>"OV_SERVER_CERT_EE", "algorithm"=>"", "size"=>4096, "description"=>"", "caa_issuers"=>nil, "host"=>nil, "admin_host"=>nil, "ekus"=>nil, "end_entity"=>nil, "ca_name"=>nil, "type"=>"EndEntityProfile", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>53, "ref"=>"3002", "friendly_name"=>"EV_SERVER_CERT_EE", "profile_name"=>"EV_SERVER_CERT_EE", "algorithm"=>"", "size"=>4096, "description"=>"", "caa_issuers"=>nil, "host"=>nil, "admin_host"=>nil, "ekus"=>nil, "end_entity"=>nil, "ca_name"=>nil, "type"=>"EndEntityProfile", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>54, "ref"=>"3003", "friendly_name"=>"CS_CERT_EE", "profile_name"=>"CS_CERT_EE", "algorithm"=>"", "size"=>4096, "description"=>"", "caa_issuers"=>nil, "host"=>nil, "admin_host"=>nil, "ekus"=>nil, "end_entity"=>nil, "ca_name"=>nil, "type"=>"EndEntityProfile", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>55, "ref"=>"3004", "friendly_name"=>"EV_CS_CERT_EE", "profile_name"=>"EV_CS_CERT_EE", "algorithm"=>"", "size"=>4096, "description"=>"", "caa_issuers"=>nil, "host"=>nil, "admin_host"=>nil, "ekus"=>nil, "end_entity"=>nil, "ca_name"=>nil, "type"=>"EndEntityProfile", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil},
  {"id"=>56, "ref"=>"3005", "friendly_name"=>"OV_CLIENTAUTH_CERT_EE", "profile_name"=>"OV_CLIENTAUTH_CERT_EE", "algorithm"=>"", "size"=>4096, "description"=>"", "caa_issuers"=>nil, "host"=>nil, "admin_host"=>nil, "ekus"=>nil, "end_entity"=>nil, "ca_name"=>nil, "type"=>"EndEntityProfile", "client_cert"=>nil, "client_key"=>nil, "client_password"=>nil}
])

Cdn.connection.truncate(Cdn.table_name)
Cdn.create!([
  {ssl_account_id: 466430, api_key: "8f213487af4f47fc609590892cc292a91b48af0b", resource_id: nil, custom_domain_name: nil, certificate_order_id: nil, is_ssl_req: false},
  {ssl_account_id: 474111, api_key: "d5e91eea0d36357424ebc6ca90519bdf8c98280c57fef5546c", resource_id: nil, custom_domain_name: nil, certificate_order_id: nil, is_ssl_req: false},
  {ssl_account_id: 474113, api_key: "97c1a433aa1fe69c5e8d79e5621c42360c4a9d0bc910782499", resource_id: nil, custom_domain_name: nil, certificate_order_id: nil, is_ssl_req: false}
])

ResellerTier.connection.truncate(ResellerTier.table_name)
ResellerTier.create!([
  {label: "1", description: {"ideal_for"=>"pay as you go"}, amount: 0, roles: "tier_1_reseller", published_as: "live"},
  {label: "2", description: {"ideal_for"=>"professionals"}, amount: 20000, roles: "tier_2_reseller", published_as: "live"},
  {label: "3", description: {"ideal_for"=>"small to medium sized businesses"}, amount: 100000, roles: "tier_3_reseller", published_as: "live"},
  {label: "4", description: {"ideal_for"=>"large businesses"}, amount: 500000, roles: "tier_4_reseller", published_as: "live"},
  {label: "5", description: {"ideal_for"=>"enterprise organizations"}, amount: 2000000, roles: "tier_5_reseller", published_as: "live"},
  {label: "west.com", description: {:name=>"west.com tier"}, amount: nil, roles: nil, published_as: "live"},
  {label: "6", description: {"ideal_for"=>"enterprise organizations"}, amount: 3500000, roles: "tier_6_reseller", published_as: "live"},
  {label: "7", description: {"ideal_for"=>"enterprise organizations"}, amount: 5000000, roles: "tier_7_reseller", published_as: "live"},
  {label: "1", description: {"ideal_for"=>"pay as you go"}, amount: 0, roles: "tier_1_reseller", published_as: "live"},
  {label: "2", description: {"ideal_for"=>"professionals"}, amount: 20000, roles: "tier_2_reseller", published_as: "live"},
  {label: "3", description: {"ideal_for"=>"small to medium sized businesses"}, amount: 100000, roles: "tier_3_reseller", published_as: "live"},
  {label: "4", description: {"ideal_for"=>"large businesses"}, amount: 500000, roles: "tier_4_reseller", published_as: "live"},
  {label: "5", description: {"ideal_for"=>"enterprise organizations"}, amount: 2000000, roles: "tier_5_reseller", published_as: "live"},
  {label: "west.com", description: {:name=>"west.com tier"}, amount: nil, roles: nil, published_as: "live"},
  {label: "6", description: {"ideal_for"=>"enterprise organizations"}, amount: 3500000, roles: "tier_6_reseller", published_as: "live"},
  {label: "7", description: {"ideal_for"=>"enterprise organizations"}, amount: 5000000, roles: "tier_7_reseller", published_as: "live"}
])

Db.delete_all
Db.create!([
  {name: "sandbox_ssl_com", host: nil, username: nil, password: nil}
])

ReminderTrigger.connection.truncate(ReminderTrigger.table_name)
ReminderTrigger.create!([
  {name: 1},
  {name: 2},
  {name: 3},
  {name: 4},
  {name: 5}
])

Role.connection.truncate(Role.table_name)
Role.create!([
  {name: "reseller", ssl_account_id: nil, description: "Reseller.", status: nil},
  {name: "sysadmin", ssl_account_id: nil, description: "Permissions to everything except SSL.com CA.", status: nil},
  {name: "owner", ssl_account_id: nil, description: "Access to all tasks related to managing entire account and team including transferring ownership of the team.", status: nil},
  {name: "affiliate", ssl_account_id: nil, description: "Affiliate.", status: nil},
  {name: "super_user", ssl_account_id: nil, description: "All permissions to everything.", status: nil},
  {name: "account_admin", ssl_account_id: nil, description: "Access to all tasks related to managing entire account and team except altering user who owns the ssl team.", status: nil},
  {name: "billing", ssl_account_id: nil, description: "Access to billing tasks for team. Tasks include creating or deleting billing profiles, managing transactions and renewing certificate orders.", status: nil},
  {name: "validations", ssl_account_id: nil, description: "Access to validation tasks for the Team. Tasks include uploading validation documents, selecting the validation method, and other related tasks.", status: nil},
  {name: "installer", ssl_account_id: nil, description: "Access to completed certificate and site seal, also has the ability to submit initial CSR and rekey/reprocess the certificate.", status: nil},
  {name: "users_manager", ssl_account_id: nil, description: "Manage teams' users. Tasks include inviting users to team, removing, editing roles, disabling and enabling teams' users.", status: nil},
  {name: "ra_admin", ssl_account_id: nil, description: "Can manage RA system settings like product configurations and mappings.", status: nil},
  {name: "individual_certificate", ssl_account_id: nil, description: "Access to only certificate orders assigned to this user in a given team.", status: nil}
])

Schedule.connection.truncate(Schedule.table_name)
Schedule.create!([
  {notification_group_id: 1, schedule_type: "Simple", schedule_value: "2"}
])

ValidationRule.connection.truncate(ValidationRule.table_name)
ValidationRule.create!([
  {description: "domain validation", operator: "AND", parent_id: nil, applicable_validation_methods: ["automatic domain lookup", "manual domain lookup"], required_validation_methods: nil, required_validation_methods_operator: "AND", notes: nil},
  {description: "notorized corporation", operator: "AND", parent_id: nil, applicable_validation_methods: ["articles of incorporation", "certificate of formation", "charter documents", "business license", "doing business as", "registration of trade name", "partnership papers", "fictitious name statement", "vendor/reseller/merchant license", "merchant certificate"], required_validation_methods: ["articles of incorporation", "certificate of formation"], required_validation_methods_operator: "OR", notes: nil},
  {description: "notorized entity", operator: "AND", parent_id: nil, applicable_validation_methods: ["articles of incorporation", "certificate of formation", "charter documents", "business license", "doing business as", "registration of trade name", "partnership papers", "fictitious name statement", "vendor/reseller/merchant license", "merchant certificate"], required_validation_methods: nil, required_validation_methods_operator: "AND", notes: nil},
  {description: "organization validation", operator: "AND", parent_id: nil, applicable_validation_methods: ["articles of incorporation", "certificate of formation", "charter documents", "business license", "doing business as", "registration of trade name", "partnership papers", "fictitious name statement", "vendor/reseller/merchant license", "merchant certificate"], required_validation_methods: nil, required_validation_methods_operator: "AND", notes: nil}
])

%w[antarr leo daniel soi dustin].each do |login|
  next if  User.exists?(login: login)

  user = User.create!(login: login, email: "#{login}@ssl.com", password: "Password123!", password_confirmation: "Password123!", status: "enabled")
  user.elevate_role(Role::SYS_ADMIN)
  user.activate!(user: {password: "Password123!", password_confirmation: "Password123!"})
  user.deliver_auto_activation_confirmation!
end unless Rails.env.test?

Dir[File.join(Rails.root, 'db', 'seeds/', '*.rb')].sort.each do |seed|
  load seed
end

Pillar::Engine.load_seed
