puts "  + Building Blocklist Entries"
Pillar::Authority::BlocklistEntry.connection.truncate(Pillar::Authority::BlocklistEntry.table_name)
Pillar::Authority::BlocklistEntry.create!([
  { pattern: '^equifax\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^hamdami\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^sis\.gov\.uk', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^yahoo\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^twitter\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^wordpress\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^cia\.gov', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^oracle\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^friends\.walla\.co\.il', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^goog\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  # { pattern: '^ssl\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^google\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^whatsapp\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^facebook\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^apple\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^microsoft\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^paypal\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^mozilla\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^gmail\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^certlock\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^android\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '^azadegi\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.live\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.10million\.org', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.balatarin\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.cybertrust\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  # { pattern: '.*?\.ssl\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.?facebook\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.google\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.whatsapp\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.apple\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.microsoft\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.paypal\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.mozilla\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.gmail\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.goog\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.?github\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.?amazon\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.?cloudapp\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.certlock\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.android\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.aol\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.azadegi\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.comodo\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.digicert\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.yahoo\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.entrust\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.godaddy\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.oracle\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.globalsign\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.JanamFadayeRahbar\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.logmein\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.mossad\.gov\.il', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.mozilla\.org', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.RamzShekaneBozorg\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.SahebeDonyayeDigital\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.skype\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.startssl\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.thawte\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.torproject\.org', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.walla\.co\.il', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.windowsupdate\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: '.*?\.wordpress\.com', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'Comodo Root CA', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'CyberTrust Root CA', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'DigiCert Root CA', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'Equifax Root CA', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'Thawte Root CA', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'GlobalSign Root CA', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'VeriSign Root CA', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'global trustee', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'amzn', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'ssltools', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' },
  { pattern: 'certchat', common_name: true, description: '', organization: false, organization_unit: false, location: false, state: nil, country: false, type: 'Pillar::Authority::BlocklistEntryTypes::Highrisk' }
])

['.*?\.ssl\.com', '.*?\.certlock\.com', '^certlock\.com', '^ssl\.com'].each do |pattern|
  blocklist_entry = Pillar::Authority::BlocklistEntry.find_by_pattern(pattern)

  if blocklist_entry.present?
    ["492_127","491_981","474_187","493_588","492_759","497_080","474_299","477_317","464_808"].each do |account_id|
      blocklist_entry.blocklist_entry_exemptions.build(account_id: account_id)
      blocklist_entry.save
    end
  end
end
