require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SurlsController do

  def mock_surl(stubs={})
    @mock_surl ||= mock_model(Surl, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all surls as @surls" do
      Surl.stub(:all) { [mock_surl] }
      get :index
      assigns(:surls).should eq([mock_surl])
    end
  end

  describe "GET show" do
    it "assigns the requested surl as @surl" do
      Surl.stub(:find).with("37") { mock_surl }
      get :show, :id => "37"
      assigns(:surl).should be(mock_surl)
    end
  end

  describe "GET new" do
    it "assigns a new surl as @surl" do
      Surl.stub(:new) { mock_surl }
      get :new
      assigns(:surl).should be(mock_surl)
    end
  end

  describe "GET edit" do
    it "assigns the requested surl as @surl" do
      Surl.stub(:find).with("37") { mock_surl }
      get :edit, :id => "37"
      assigns(:surl).should be(mock_surl)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created surl as @surl" do
        Surl.stub(:new).with({'these' => 'params'}) { mock_surl(:save => true) }
        post :create, :surl => {'these' => 'params'}
        assigns(:surl).should be(mock_surl)
      end

      it "redirects to the created surl" do
        Surl.stub(:new) { mock_surl(:save => true) }
        post :create, :surl => {}
        response.should redirect_to(surl_url(mock_surl))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved surl as @surl" do
        Surl.stub(:new).with({'these' => 'params'}) { mock_surl(:save => false) }
        post :create, :surl => {'these' => 'params'}
        assigns(:surl).should be(mock_surl)
      end

      it "re-renders the 'new' template" do
        Surl.stub(:new) { mock_surl(:save => false) }
        post :create, :surl => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested surl" do
        Surl.stub(:find).with("37") { mock_surl }
        mock_surl.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :surl => {'these' => 'params'}
      end

      it "assigns the requested surl as @surl" do
        Surl.stub(:find) { mock_surl(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:surl).should be(mock_surl)
      end

      it "redirects to the surl" do
        Surl.stub(:find) { mock_surl(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(surl_url(mock_surl))
      end
    end

    describe "with invalid params" do
      it "assigns the surl as @surl" do
        Surl.stub(:find) { mock_surl(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:surl).should be(mock_surl)
      end

      it "re-renders the 'edit' template" do
        Surl.stub(:find) { mock_surl(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested surl" do
      Surl.stub(:find).with("37") { mock_surl }
      mock_surl.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the surls list" do
      Surl.stub(:find) { mock_surl }
      delete :destroy, :id => "1"
      response.should redirect_to(surls_url)
    end
  end

end
