class SslcomCaRevocationRequest < CaApiRequest
  REASONS = %w(UNSPECIFIED)

  # REASONS = %w(UNSPECIFIED  KEYCOMPROMISE  CACOMPROMISE  AFFILIATIONCHANGED  SUPERSEDED  CESSATIONOFOPERATION
  #           CERTIFICATEHOLD  REMOVEFROMCRL  PRIVILEGESWITHDRAWN  AACOMPROMISE)
  #
end
