class Api::V1::UserSerializer < Api::V1::BaseSerializer
  attribute  :active
  attribute  :address1
  attribute  :address2
  attribute  :address3
  attribute  :authy_user
  attribute  :avatar_content_type
  attribute  :avatar_file_name
  attribute  :avatar_file_size
  attribute  :avatar_updated_at
  attribute  :city
  attribute  :country
  attribute  :current_login_at
  attribute  :current_login_ip
  attribute  :default_ssl_account
  attribute  :duo_enabled
  attribute  :email
  attribute  :failed_login_count
  attribute  :first_name
  attribute  :is_auth_token
  attribute  :last_login_at
  attribute  :last_login_ip
  attribute  :last_name
  attribute  :last_request_at
  attribute  :login
  attribute  :login_count
  attribute  :main_ssl_account
  attribute  :max_teams
  attribute  :openid_identifier
  attribute  :organization
  attribute  :phone
  attribute  :phone_prefix
  attribute  :po_box
  attribute  :postal_code
  attribute  :state
  attribute  :status
  attribute  :created_at
  attribute  :updated_at
end
